<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RayShineBackend</AssemblyName>
    <ApplicationIcon>..\..\assets\RayShine.ico</ApplicationIcon>
    <Version>0.0.4</Version>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\WindowsExecutableLocator.cs" Link="WindowsExecutableLocator.cs" />
  </ItemGroup>
</Project>
